version: '3'
services:
  surname:
    build: surname-app
    networks:
      - hello-net
    volumes:
      - ./data:/usr/app/data
  hello:
    build: hello-app
    ports:
      - "8090:8080"
    networks:
      - hello-net
networks:
  hello-net:
    driver: bridge
