version: '3'
services:
  surname:
    build: surname-app
    ports:
      - "8081:8080"
    networks:
      - hello-net
  hello:
    build: hello-app
    ports:
      - "8082:8080"
    networks:
      - hello-net
networks:
  hello-net:
    driver: bridge
