version: '3'
services:
  surname:
    build: surname-app
    networks:
      - hello-net
  hello:
    build: hello-app
    networks:
      - hello-net
  load-balancer:
    image: dockercloud/haproxy:latest
    links:
      - hello
    ports:
      - "80:80"
    networks:
      - hello-net
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
networks:
  hello-net:
    driver: bridge
